### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by aaron-plahn**
- Downsized images and uploaded them to OB.
- Now pulling background images from OBServer.
- Set social links to open in new tab.

-Aaron

### CODE REVIEW

**Comment by jbambrick** [comment]
Hey Aaron,


Yes, I was going to email the downsized pictures but the server went down. But while the e-mails were down I worked on the language website and have started the FV mockup. The radio stream link is set on the language website and I cleaned up a bunch of unnecessary code.


Justin

________________________________

**Comment by aaron-plahn** [comment]
Good work, Justin. It’s great to hear from you.

I’ve simultaneously been making changes to the original
tsilhqotin-radio-website. Could you accept my pull request (if you haven’t
already) to that? Note I am now able to pull images from the
OpenBroadcaster (instead of ’assets’ folder). I resized and uploaded all
assets for the radio website to the OpenBroadcaster server. I’ll give you
some instructions for doing more of that, but we’ll probably use strapi for
most of our assets.

Have you committed your latest edits to the language website? Let me know
when it’s ready for me to have a turn. I’m going to go pretty hard on that
early next week so we can get it published (with your radio player as part
of that.

How is the FV mockup coming?

I want to go hard on the LanguageWebsite, pivoting towards working really
hard on the dictionary, word lists, and paradigms as soon as the new site
is live. I’m working on paradigms and organizing and analyzing text data
now. Also working on a cool text processing library.

Take Care,

Aaron

**Comment by jbambrick** [comment]
Yes, I accepted the pull request on the tsilhqotin-radio-website. I've committed my latest changes to the branch tsilhqotin-language-website-radio . I think it is ready for you to have a turn, let me know if there's anything that needs correcting. That'll be exciting to see the website published. The mockup is going fine right now.


Is the radio signal back up? I haven't drove by the office and checked the signal.


Justin

________________________________

**Comment by jbambrick** [comment]
I just added a small change to the backgrounds of the navbar and certain divs, its up on github. The firefox browser doesn't support the blur filter yet so I added color so that there is contrast from the background and the page content.


Justin

________________________________

**Pull request merged**
